### ISSUE TITLE
Glass v4.0.0 Checklist

### ISSUE THREAD

**Issue by Paperworx** [BlocklandGlass/BlocklandGlass#131]
- [x] Fix: Comment box's text goes off screen in MM when typing long.
- [x] Fix: Not being able to join passworded servers from the Glass Server Preview window or the "Join" button in user windows.
- [x] Fix: Attempt to find a way to have NotificationManager not spam the console with trace enabled.
- [x] Fix: Filename in add-on page (MM) overflowing the swatch if it's too long.
- [x] Fix: When a friend disconnects from Glass, their last joined server still shows up (it should be blank / reset) in their Glass User window.
- [x] Fix: MM 'My Colorsets' Blockland/RTB/Glass icons not being displayed at all (probably just a simple swatch .pos issue).
- [x] Fix: Glass Overlay - Display Vignette setting: is hiding the entire overlay, not just the vignette.
- [x] Fix: Glass Server Preferences - Categories have extra white space in swatch.
- [x] Fix: Friend List: Avatar defaulting to black for some reason.
- [x] Complete: Use Glass Live User cache for Glass Moderation user list, so it displays users who disconnected as well as presently connected users?
- [x] Complete: RTB <-> Glass Preferences Synchronization [CANCELLED]
- [x] Complete: Server name change via Glass Preferences -> update name to all clients currently connected to server (not sure if this was ever implemented).
- [x] Complete: "Search by author" working with RTB archive checkbox option?
- [x] Complete: Not being able to load a user's avatar = replace with pure black character placeholder.
- [x] Complete: Loading screens CRC functionality -- not done.
- [x] Complete: Manual documentation.
- [x] Complete: AFK detection.
- [x] Complete: Inviting.
- [x] Complete: MM rating system.
- [x] Complete: Make server pref/admin manager window larger.
- [x] Complete: Glass Live - Friend Requests / Friends / Blocked: open or closed persistence.
- [x] Complete: Glass Settings - Missing description text in text list swatches type.
- [x] Complete: Glass Settings: Privacy settings (show avatar, show location).
- [x] Complete: Glass MM - Add page persistence (moving back to category after viewing add-on page = resets to page one, not previous page you were on).
- [x] Complete: Support_Preferences version below 1.2.0 warning -- versions != 1.2.0 == broken af.
- [ ] Complete: Glass Live: Apply disc. filter to usernames (stop them from connecting).
