### ISSUE TITLE
3.2.0 Checklist

### ISSUE THREAD

**Issue by Paperworx** [BlocklandGlass/BlocklandGlass#78]
- [x] Ability to pick your user icon.
- [x] Add DM message if the user you're trying to reach has blocked you.
- [x] When a user goes offline, have status set to "offline". Also set .online to true/false respectively for backwards compatibility.
- [x] Muting = setIcon to sound_mute, then reset to previous icon after unmute.
- [x] Chatroom joining/leaving.
- [x] AFK detection for automated 'away' status **(leave to 3.x.x)**
- [x] Glass settings "RESET" (to defaults) button **(leave to 3.x.x)**
- [x] Deny auth if username = "GlassBot" or username is a blocked word.
- [x] Chatroom moderation (kick, ban, mute, banid, muteid, motd).
- [x] Chatroom general commands (help, time, uptime).
- [x] Chatroom anti-spam (sending same message twice, sending messages too fast, specific words).
- [x] User blocking: block DMs, chatroom messages.
- [x] User blocking: block future friend requests from blocked user.
- [x] User blocking: remove friend requests from blocked user.
- [x] Setting to disable auto-join of chatroom.
- [x] Fix double connection issue.
- [x] Chatroom moderation (forceicon, announce, moveto[room]).
- [x] Reset everybody's settings on update to 3.2.0.
- [x] Backwards compatibility + testing: does the 3.2.0 Glass server work with pre 3.2.0 Glass clients? (online status, DMing, chatrooms, etc)
